version: "3.8"
# @TODO ヘルスチェック、Nginxリバースプロキシは後ほど
services:
  gin-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    # ヘルスチェックを無効化
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "wget",
    #       "--quiet",
    #       "--tries=1",
    #       "--spider",
    #       "http://localhost:8080/health",
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # # オプション: Nginxリバースプロキシ
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - gin-app
  #   restart: unless-stopped
